#This is a wrapper for RAVEN/TRiAGE
#It should be user-friendly and use 
#final functions


#===============================================================
# set experimental parameters
#===============================================================

exp.name = "trait_svm_DEG"
p.or.q <- 0.01
trait.genes.svm.trials <- 100

#===============================================================
# check whether we are on the cluster or hpcdata machine
#===============================================================

	cur.dir <- getwd()
	test.dir <- strsplit(cur.dir, "home")
	if(length(test.dir[[1]]) > 1){on.cluster = TRUE}else{on.cluster = FALSE}
	if(on.cluster){
		code.dir <- "/home/atyler/code/"
		project.dir <- "/home/atyler/SSc/"
		project.data.dir <- paste0(project.dir, "data/")
		results.dir <- paste0(project.dir, "Results/", exp.name, "_", p.or.q, "/")
		useful.scripts.dir <- paste0(code.dir, "useful_r_code/")
		triage.dir <- paste0(code.dir, "TRiAGE")
		}else{
		code.dir <- "~/Documents/git_repositories/"
		project.dir <- "~/Documents/Data/Scleroderma/RAVEN/trait.svm"
		project.data.dir <- "~/Documents/Data/Scleroderma/RAVEN"
		useful.scripts.dir <- paste0(code.dir, "useful_r_code")
		triage.dir <- paste0(code.dir, "raven")
		results.dir <- paste0(project.dir, exp.name, "_", p.or.q, "/")
		}


#===============================================================
# load all the necessary libraries
needed.packages <- c("evd", "Matrix", "fdrtool", "shape", "corpcor", "RColorBrewer", "doParallel", "foreach", "caTools", "stringr", "abind", "qpcR")

	if(on.cluster){
	all.packages <- installed.packages(lib.loc = "/home/atyler/R/x86_64-pc-linux-gnu-library/3.4")
	
	package.locale <- match(needed.packages, all.packages[,1])
	missing.packages <- needed.packages[which(is.na(package.locale))]
	
	if(length(missing.packages) > 0){install.packages(missing.packages, lib = "/home/atyler/R/x86_64-pc-linux-gnu-library/3.4", repos = "https://cloud.r-project.org")}
	}else{
	library(biomaRt)	
	lib <- useMart("ENSEMBL_MART_ENSEMBL", dataset = "mmusculus_gene_ensembl", host = "may2017.archive.ensembl.org")
	}


for(i in 1:length(needed.packages)){library(needed.packages[i], character.only = TRUE)}
#===============================================================


#===============================================================
#source all the code from needed packages
#===============================================================

setwd(useful.scripts.dir)
all.fun <- list.files(pattern = ".R")
if(length(all.fun) > 0){for(i in 1:length(all.fun)){source(all.fun[i])}}

setwd(triage.dir)
all.fun <- list.files(pattern = "*.R")
for(i in 1:length(all.fun)){source(all.fun[i])}

setwd(project.data.dir)


#=======================================================
#read in all the data generated by anaphylaxis_TRiAGE.R
#=======================================================

tissue.net <- readRDS("skin_top.RData")

if(!file.exists(results.dir)){system(paste("mkdir", results.dir))}
setwd(results.dir)
	


#=======================================================
#find the genes that are correlated with the traits of
#interest
#=======================================================

sig.gene.info <- as.matrix(read.table(paste0(project.data.dir, "/DEG.by.SSc.p.", p.or.q, ".txt"), sep = "\t", stringsAsFactors = FALSE, header = FALSE, strip.white = TRUE))

#====================================================================
# If using SVM to identify trait-related genes:
# build the tissue-specific adjacency matrix for MPO-associated 
# genes
#====================================================================
tissue.mat <- tissue.adj.mat(tissue.net = tissue.net, gene.list = as.numeric(sig.gene.info[,1]), inc.all.genes = TRUE)
tissue.mat <- remove.unconnected.tp(tissue.mat = tissue.mat)
saveRDS(tissue.mat, "Tissue.Matrix.RData")

orig.cost.list <- 10^seq(-5, 2, 1)
tuned.cost.list <- tune.cost.parameter(tissue.mat, n.trials = 1, C.list = orig.cost.list, verbose = TRUE)

svm.pheno.genes <- tissue.svm(tissue.mat = tissue.mat, n.trials = trait.genes.svm.trials, C.list = tuned.cost.list, vote.min = 0.5, verbose = TRUE)
saveRDS(svm.pheno.genes, "SVM.Pheno.Genes.RData")
	
